ARG NODE_VERSION=20.11.0

FROM node:$NODE_VERSION-buster as production

ARG CLIENT_HOST

WORKDIR /app

RUN echo $CLIENT_HOST

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn lerna bootstrap
RUN rm -rf /app/packages/client/dist/ && yarn build --scope=client

EXPOSE 3000
CMD [ "yarn", "preview:client" ]
