ARG NODE_VERSION=18
ARG CLIENT_HOST
ARG SERVER_HOST

FROM node:$NODE_VERSION-buster as production

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn lerna bootstrap
RUN rm -rf /app/packages/client/dist/ && yarn build --scope=client

EXPOSE 3000
CMD [ "yarn", "preview:client" ]
