version: '3.9'

services:
  nginxproxymanager:
    container_name: nginxproxymanager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - nginxproxymanager:/data
      - letsencrypt:/etc/letsencrypt
  client:
    container_name: practicum-client
    image: cr.yandex/${ID_REGISTRY}/grozzzny/cat-pairs/client:${TAG}
    restart: always
    ports:
      - '3000:3000'
    environment:
      CLIENT_HOST: ${CLIENT_HOST}
      SERVER_HOST: ${SERVER_HOST}
      NODE_ENV: production
    depends_on:
      server:
        condition: service_started
      postgresdb:
        condition: service_healthy
  server:
    container_name: practicum-server
    image: cr.yandex/${ID_REGISTRY}/grozzzny/cat-pairs/server:${TAG}
    restart: always
    ports:
      - '3001:3001'
    environment:
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      postgresdb:
        condition: service_healthy
  postgresdb:
    container_name: postgresdb
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
    volumes:
      - postgresdata:/var/lib/postgresql/dat
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready',
          '-q',
          '-h',
          'localhost',
          '-p',
          '${POSTGRES_PASSWORD}',
          '-U',
          '${POSTGRES_USER}',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '15432:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      postgresdb:
        condition: service_healthy
volumes:
  postgresdata:
  nginxproxymanager:
  letsencrypt:
  pgadmin:
