version: '3.9'

services:
  nginxproxymanager:
    container_name: nginxproxymanager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - nginxproxymanager:/data
      - letsencrypt:/etc/letsencrypt
  client:
    container_name: practicum-client
    image: ghcr.io/grozzzny/cat-pairs/client:dev
    restart: always
    ports:
      - '3000:3000'
    environment:
      CLIENT_HOST: https://cat-pairs.online
      SERVER_HOST: https://api.cat-pairs.online
      NODE_ENV: production
    depends_on:
      server:
        condition: service_started
      postgresdb:
        condition: service_healthy
  server:
    container_name: practicum-server
    image: ghcr.io/grozzzny/cat-pairs/server:dev
    restart: always
    ports:
      - '3001:3001'
    environment:
      SERVER_PORT: 3001
      POSTGRES_HOST: postgresdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
      SECRET_KEY: 12341232341234e
    depends_on:
      postgresdb:
        condition: service_healthy
  postgresdb:
    container_name: postgresdb
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGUSER: postgres
    volumes:
      - postgresdata:/var/lib/postgresql/dat
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready',
          '-q',
          '-h',
          'localhost',
          '-p',
          'postgres',
          '-U',
          'postgres',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '15432:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@cat-pairs.online'
      PGADMIN_DEFAULT_PASSWORD: 'asd9sadfnnwefHHse8'
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      postgresdb:
        condition: service_healthy
volumes:
  postgresdata:
  nginxproxymanager:
  letsencrypt:
  pgadmin:
