export { GamePage } from './game-page';
export { MainPage } from './main-page';
export { ForumPage } from './forum-page';
export { LoginPage } from './login-page';
export { RegistrationPage } from './registration-page';
export { ProfilePage } from './profile-page';
export { LeaderboardPage } from './leaderboard-page';
export { Page404 } from './page-404';
export { StartGamePage } from './startgame-page';
